CREATE DATABASE IF NOT EXISTS k8s CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE k8s;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  groups TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS approval_history (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  creator_id VARCHAR(36) NOT NULL,
  approvers JSON NOT NULL,
  steps JSON NOT NULL,
  records JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  metadata JSON,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

